# Generated by Django 3.2 on 2021-05-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Username'),
        ),
    ]
