# Generated by Django 3.2 on 2021-04-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='image_link',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Image link'),
        ),
    ]
