# Generated by Django 3.2 on 2021-04-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbase', '0002_alter_posting_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='facts',
        ),
        migrations.AddField(
            model_name='posting',
            name='fact',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='fact'),
        ),
    ]
