# Generated by Django 3.2 on 2021-04-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbase', '0002_auto_20210415_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='image',
        ),
        migrations.AddField(
            model_name='posting',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
