"""
Django settings for AirPages project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u0e6&ug_uiupakzy4ur*@^p5+vt0y%qq31hy#8d4_0&v5jt#_t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'airbase'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'AirPages.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AirPages.wsgi.application'

CORS_ORIGIN_ALLOW_ALL = True


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

if 'ec2-user' in os.environ['USER']:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'airpages',
            'USER': 'rwiggles',
            'PASSWORD': 'databases',
            'HOST': 'airpages-db-instance-1.czk0wah8t0bg.us-east-1.rds.amazonaws.com',
            'PORT': '3306',
            'CONN_MAX_AGE': 20,
            },
        'replica2': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'airpages',
            'USER': 'rwiggles',
            'PASSWORD': 'databases',
            'HOST': 'airpages-db-read-replica-2.czk0wah8t0bg.us-east-1.rds.amazonaws.com',
            'PORT': '3306',
            'CONN_MAX_AGE': 20,
        },
        'replica3': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'airpages',
            'USER': 'rwiggles',
            'PASSWORD': 'databases',
            'HOST': 'airpages-db-read-replica-3.czk0wah8t0bg.us-east-1.rds.amazonaws.com',
            'PORT': '3306',
            'CONN_MAX_AGE': 20,
        },
        'replica4': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'airpages',
            'USER': 'rwiggles',
            'PASSWORD': 'databases',
            'HOST': 'airpages-db-read-replica-4.czk0wah8t0bg.us-east-1.rds.amazonaws.com',
            'PORT': '3306',
            'CONN_MAX_AGE': 20,
        },
        'replica5': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'airpages',
            'USER': 'rwiggles',
            'PASSWORD': 'databases',
            'HOST': 'airpages-db-read-replica-5.czk0wah8t0bg.us-east-1.rds.amazonaws.com',
            'PORT': '3306',
            'CONN_MAX_AGE': 20,
        },

    }
    DATABASE_ROUTERS = ['database_routers.CustomRouter']

else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
